# Generated by Django 3.1.1 on 2022-01-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211226_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nome',
            new_name='name',
        ),
    ]
